version: '3'

services:
  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: secret
  redis-insight:
    image: redis/redisinsight:latest
    restart: always
    ports:
      - "5540:5540"
    volumes:
      - redis-insight:/data
  command-mysql:
    image: mysql:5.7
    container_name: command-mysql2
    platform: linux/amd64
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: commandcep
      MYSQL_PASSWORD: root
    volumes:
      - ./mysql:/var/lib/mysql
  query-mysql:
    image: mysql:5.7
    container_name: query-mysql2
    platform: linux/amd64
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: querycep
      MYSQL_PASSWORD: root
    volumes:
      - ./querymysql:/var/lib/mysql

volumes:
  redis-insight:
