version: '3'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: secret

  redis-insight:
    image: redis/redisinsight:latest
    ports:
      - "5540:5540"
    volumes:
      - redis-insight:/data

  command-mysql:
    image: mysql:5.7
    container_name: command-mysql
    platform: linux/amd64
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: commandcep
      MYSQL_PASSWORD: root
    volumes:
      - ./mysql:/var/lib/mysql

  rabbitmq:
    image: "rabbitmq:3.8.6-management"
    container_name: rabbitmq-masterdev
    ports:
      - 5672:5672
      - 15672:15672

  fts-eureka-server:
    build:
      context: ./fts-eureka-server #indica o dir da Dockerfile
      dockerfile: dockerfile
    container_name: fts-eureka-server
    volumes:
      - ./tmp:/tmp
    ports:
      - 8761:8761
    depends_on:
      - redis
      - redis-insight
      - command-mysql
      - rabbitmq

  fts-gateway:
    build:
      context: ./fts-gateway #indica o dir da Dockerfile
      dockerfile: dockerfile
    container_name: fts-gateway
    volumes:
      - ./tmp:/tmp
    ports:
      - 8080:8080
    depends_on:
      - fts-eureka-server

  fts-cep-remote-consumer:
    build:
      context: ./fts-cep-remote-consumer #indica o dir da Dockerfile
      dockerfile: dockerfile
    volumes:
      - ./tmp:/tmp
    depends_on:
      - fts-eureka-server

  fts-cep-retriever:
    build:
      context: ./fts-cep-retriever #indica o dir da Dockerfile
      dockerfile: dockerfile
    volumes:
      - ./tmp:/tmp
    depends_on:
      - fts-eureka-server

  fts-command-ms:
    build:
      context: ./fts-command-ms #indica o dir da Dockerfile
      dockerfile: dockerfile
    volumes:
      - ./tmp:/tmp
    depends_on:
      - fts-eureka-server

  fts-query-ms:
    build:
      context: ./fts-query-ms #indica o dir da Dockerfile
      dockerfile: dockerfile
    volumes:
      - ./tmp:/tmp
    depends_on:
      - fts-eureka-server

volumes:
  redis-insight:
