version: '3'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: secret
  redis-insight:
    image: redis/redisinsight:latest
    ports:
      - "5540:5540"
    volumes:
      - redis-insight:/data
  command-mysql:
    image: mysql:5.7
    container_name: command-mysql
    platform: linux/amd64
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: commandcep
      MYSQL_PASSWORD: root
    volumes:
      - ./mysql:/var/lib/mysql
  query-mysql:
    image: mysql:5.7
    container_name: query-mysql
    platform: linux/amd64
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: querycep
      MYSQL_PASSWORD: root
    volumes:
      - ./querymysql:/var/lib/mysql
  rabbitmq:
    image: "rabbitmq:3.8.6-management"
    container_name: rabbitmq-masterdev
    ports:
      - 5672:5672
      - 15672:15672
volumes:
  redis-insight:
