spring:
  application:
    name: fts-gateway
  cloud:  
    gateway:
      routes:
        - id: fts-cep-retriever-route
          uri: lb://fts-cep-retriever
          predicates: 
          - Path=/address/**
        - id: fts-cep-remote-consumer-route
          uri: lb://fts-cep-remote-consumer
          predicates: 
          - Path=/remote/**
        - id: fts-query-ms-route
          uri: lb://fts-query-ms
          predicates: 
          - Path=/query/**
        - id: fts-command-ms-route
          uri: lb://fts-command-ms
          predicates: 
          - Path=/command/**
  main:
    web-application-type: REACTIVE

server:
  port: 8080

# Eureka server configuration
eureka: 
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance: 
    prefer-ip-address: true
